
-- Create packages table
CREATE TABLE packages (
    id SERIAL PRIMARY KEY,
    name VARCHAR(70) NOT NULL UNIQUE,
    cache_hit INTEGER NOT NULL DEFAULT 0,
    cache_miss INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
